package ar.edu.unlam.pb2.lineaFerroviria;

public enum NombreEstacion {
	ONCE,CABALLITO,FLORES,
	FLORESTA,VILLA_LURO,LINIERS,
	CIUDADELA,RAMOS_MEJIA,HAEDO,MORON,CASTELAR,
	ITUZAINGO,SANANTONIO_DE_PADUA,
	MERLO,PASO_DEL_REY,MORENO;
	
}
